#%RAML 0.8
title: Trade Port 
version: v1
baseUri: http://localhost:8081/scb/api/otp
/challenge:
  description: API for Topdanmark Mule Challenge
  post:
    description: API for Topdanmark Mule Challenge
    body: 
      application/json:
                  
    responses:
      200:
        body:
          application/json:
