server:
  port: 50200
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - text/html
      - text/xml
      - text/plain
    min-response-size: 1024
  undertow:
      buffer-size: 16000
      buffers-per-region: 10
      direct-buffers: true
      io-threads: 7
      worker-threads: 300
          
info:
  app:
    name: Challenge Mule API
    description: Challenge Mule API Microservice
    version: 1.0.0

spring:
  profiles: local
  application:
    name: challenge-api

eureka:
  enable: false
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://10.20.172.129:8761/eureka
      healthcheck:
        enabled: true
  instance:
    leaseExpirationDurationInSeconds: 30
    preferIpAddress: true
  fetchRegistry: true

health:
  config:
    enabled: false    


mule:
  max:
    pool:
      size: 30
  timeout:
    core: 1800000
config:
  resources:  
    - mule-config.xml
    - challenge.xml
    - crm-config.xml
    - distribution-config.xml
    - policy-config.xml
    
#######################################################################################################################################
#                                              Microservice Configuration                                                                 #
#######################################################################################################################################



#######################################################################################################################################
#                                              Logback Configuration                                                                 #
#######################################################################################################################################
logging:
  file: C:/data/log/local/challenge-api-slf4j.log